FROM python:3.11

RUN apt-get update && apt-get install -y \
    git \
    nano \
    curl \
    tree \
    build-essential \
    gnupg \
    && rm -rf /var/lib/apt/lists/*


# instalar Google Cloud CLI minimal
RUN echo "deb [signed-by=/usr/share/keyrings/cloud.google.gpg] http://packages.cloud.google.com/apt cloud-sdk main" \
    | tee /etc/apt/sources.list.d/google-cloud-sdk.list \
    && curl https://packages.cloud.google.com/apt/doc/apt-key.gpg \
    | gpg --dearmor \
    | tee /usr/share/keyrings/cloud.google.gpg > /dev/null \
    && apt-get update \
    && apt-get install -y google-cloud-cli \
    && rm -rf /var/lib/apt/lists/*


# criar workspace explicitamente
RUN mkdir -p /app

ENV PYTHONPATH=/app

WORKDIR /app

COPY requirements.prod.txt .
COPY requirements.dev.txt .

RUN pip install --upgrade pip \
    && pip install --no-cache-dir -r requirements.dev.txt